// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: football_details.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertMatchEvent = `-- name: UpsertMatchEvent :exec
INSERT INTO match_events (match_id, flashscore_id, type, minute, player_name, team_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (match_id, flashscore_id) DO UPDATE
SET type = EXCLUDED.type,
    minute = EXCLUDED.minute,
    player_name = EXCLUDED.player_name,
    team_id = EXCLUDED.team_id,
    updated_at = now()
`

type UpsertMatchEventParams struct {
	MatchID      pgtype.UUID
	FlashscoreID string
	Type         string
	Minute       string
	PlayerName   string
	TeamID       pgtype.UUID
}

func (q *Queries) UpsertMatchEvent(ctx context.Context, arg UpsertMatchEventParams) error {
	_, err := q.db.Exec(ctx, upsertMatchEvent,
		arg.MatchID,
		arg.FlashscoreID,
		arg.Type,
		arg.Minute,
		arg.PlayerName,
		arg.TeamID,
	)
	return err
}

const upsertMatchStats = `-- name: UpsertMatchStats :exec
INSERT INTO match_statistics (match_id, stats, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (match_id) DO UPDATE
SET stats = EXCLUDED.stats,
    updated_at = now()
`

type UpsertMatchStatsParams struct {
	MatchID pgtype.UUID
	Stats   []byte
}

func (q *Queries) UpsertMatchStats(ctx context.Context, arg UpsertMatchStatsParams) error {
	_, err := q.db.Exec(ctx, upsertMatchStats, arg.MatchID, arg.Stats)
	return err
}

const upsertPlayer = `-- name: UpsertPlayer :one
INSERT INTO players (flashscore_id, team_id, name, nationality, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (flashscore_id) DO UPDATE
SET name = EXCLUDED.name,
    nationality = EXCLUDED.nationality,
    team_id = EXCLUDED.team_id,
    updated_at = now()
RETURNING id
`

type UpsertPlayerParams struct {
	FlashscoreID string
	TeamID       pgtype.UUID
	Name         string
	Nationality  pgtype.Text
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPlayer,
		arg.FlashscoreID,
		arg.TeamID,
		arg.Name,
		arg.Nationality,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
