// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: football.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveCompetitions = `-- name: ListActiveCompetitions :many
SELECT id, slug, flashscore_path FROM competitions WHERE active AND scraped ORDER BY sort_order
`

type ListActiveCompetitionsRow struct {
	ID             pgtype.UUID
	Slug           string
	FlashscorePath string
}

func (q *Queries) ListActiveCompetitions(ctx context.Context) ([]ListActiveCompetitionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCompetitionsRow
	for rows.Next() {
		var i ListActiveCompetitionsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.FlashscorePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCandidates = `-- name: ListLiveCandidates :many
SELECT id, flashscore_id, home_team_id, away_team_id
FROM matches
WHERE status = 'live'
   OR (status = 'scheduled' AND match_time <= now() AND match_time > now() - interval '3 hours')
`

type ListLiveCandidatesRow struct {
	ID           pgtype.UUID
	FlashscoreID string
	HomeTeamID   pgtype.UUID
	AwayTeamID   pgtype.UUID
}

// Live matches, plus scheduled ones whose kick-off has passed but the league page has not caught up.
func (q *Queries) ListLiveCandidates(ctx context.Context) ([]ListLiveCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLiveCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveCandidatesRow
	for rows.Next() {
		var i ListLiveCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlashscoreID,
			&i.HomeTeamID,
			&i.AwayTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNationalTeamsToScrape = `-- name: ListNationalTeamsToScrape :many
SELECT t.flashscore_id, n.slug AS country_slug
FROM teams t
JOIN countries n ON n.id = t.country_id
WHERE EXISTS (SELECT 1 FROM competitions c WHERE c.country_id = n.id AND c.active AND c.scraped)
`

type ListNationalTeamsToScrapeRow struct {
	FlashscoreID string
	CountrySlug  string
}

// National teams of countries with a scraped league, e.g. Indonesia.
func (q *Queries) ListNationalTeamsToScrape(ctx context.Context) ([]ListNationalTeamsToScrapeRow, error) {
	rows, err := q.db.Query(ctx, listNationalTeamsToScrape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNationalTeamsToScrapeRow
	for rows.Next() {
		var i ListNationalTeamsToScrapeRow
		if err := rows.Scan(&i.FlashscoreID, &i.CountrySlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSquadsToSync = `-- name: ListSquadsToSync :many
SELECT t.id, t.flashscore_id, t.flashscore_slug::text AS flashscore_slug
FROM teams t
WHERE t.flashscore_slug IS NOT NULL
  AND (t.squad_synced_at IS NULL OR t.squad_synced_at < now() - interval '1 day')
  AND CASE WHEN t.country_id IS NULL
      THEN EXISTS (
          SELECT 1 FROM matches m JOIN competitions c ON c.id = m.competition_id
          WHERE c.active AND c.scraped AND t.id IN (m.home_team_id, m.away_team_id))
      ELSE EXISTS (
          SELECT 1 FROM competitions c WHERE c.country_id = t.country_id AND c.active AND c.scraped)
      END
ORDER BY t.squad_synced_at NULLS FIRST
LIMIT $1
`

type ListSquadsToSyncRow struct {
	ID             pgtype.UUID
	FlashscoreID   string
	FlashscoreSlug string
}

// Clubs playing a scraped competition, and national teams of countries with
// one (Indonesia), whose squad was not read in the last day, oldest first.
func (q *Queries) ListSquadsToSync(ctx context.Context, limit int32) ([]ListSquadsToSyncRow, error) {
	rows, err := q.db.Query(ctx, listSquadsToSync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSquadsToSyncRow
	for rows.Next() {
		var i ListSquadsToSyncRow
		if err := rows.Scan(&i.ID, &i.FlashscoreID, &i.FlashscoreSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsMissingLogo = `-- name: ListTeamsMissingLogo :many
SELECT id, flashscore_id, logo_source_url::text AS logo_source_url
FROM teams
WHERE logo_url IS NULL AND logo_source_url IS NOT NULL
`

type ListTeamsMissingLogoRow struct {
	ID            pgtype.UUID
	FlashscoreID  string
	LogoSourceUrl string
}

func (q *Queries) ListTeamsMissingLogo(ctx context.Context) ([]ListTeamsMissingLogoRow, error) {
	rows, err := q.db.Query(ctx, listTeamsMissingLogo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsMissingLogoRow
	for rows.Next() {
		var i ListTeamsMissingLogoRow
		if err := rows.Scan(&i.ID, &i.FlashscoreID, &i.LogoSourceUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSquadSynced = `-- name: MarkSquadSynced :exec
UPDATE teams SET squad_synced_at = now() WHERE id = $1
`

func (q *Queries) MarkSquadSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSquadSynced, id)
	return err
}

const setTeamLogo = `-- name: SetTeamLogo :exec
UPDATE teams SET logo_url = $2 WHERE id = $1
`

type SetTeamLogoParams struct {
	ID      pgtype.UUID
	LogoUrl pgtype.Text
}

func (q *Queries) SetTeamLogo(ctx context.Context, arg SetTeamLogoParams) error {
	_, err := q.db.Exec(ctx, setTeamLogo, arg.ID, arg.LogoUrl)
	return err
}

const updateMatchLive = `-- name: UpdateMatchLive :exec
UPDATE matches
SET status = $2, stage = $3, stage_started_at = $4, home_score = $5, away_score = $6,
    data_as_of = now(), updated_at = now()
WHERE id = $1
`

type UpdateMatchLiveParams struct {
	ID             pgtype.UUID
	Status         string
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
}

func (q *Queries) UpdateMatchLive(ctx context.Context, arg UpdateMatchLiveParams) error {
	_, err := q.db.Exec(ctx, updateMatchLive,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.StageStartedAt,
		arg.HomeScore,
		arg.AwayScore,
	)
	return err
}

const upsertCountry = `-- name: UpsertCountry :one
INSERT INTO countries (slug, name) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET slug = EXCLUDED.slug
RETURNING id
`

type UpsertCountryParams struct {
	Slug string
	Name string
}

func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCountry, arg.Slug, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (flashscore_id, competition_id, season, home_team_id, away_team_id, status, match_time, home_score, away_score, stage, stage_started_at, round, phase, data_as_of, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now(), now())
ON CONFLICT (flashscore_id) DO UPDATE
SET status = EXCLUDED.status,
    round = EXCLUDED.round,
    phase = EXCLUDED.phase,
    season = EXCLUDED.season,
    stage = EXCLUDED.stage,
    stage_started_at = EXCLUDED.stage_started_at,
    match_time = EXCLUDED.match_time,
    home_score = EXCLUDED.home_score,
    away_score = EXCLUDED.away_score,
    data_as_of = now(),
    updated_at = now()
RETURNING id
`

type UpsertMatchParams struct {
	FlashscoreID   string
	CompetitionID  pgtype.UUID
	Season         int16
	HomeTeamID     pgtype.UUID
	AwayTeamID     pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	Round          pgtype.Text
	Phase          pgtype.Text
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMatch,
		arg.FlashscoreID,
		arg.CompetitionID,
		arg.Season,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.Status,
		arg.MatchTime,
		arg.HomeScore,
		arg.AwayScore,
		arg.Stage,
		arg.StageStartedAt,
		arg.Round,
		arg.Phase,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSquadPlayer = `-- name: UpsertSquadPlayer :exec
INSERT INTO players (flashscore_id, team_id, name, nationality, shirt_number, position, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (flashscore_id) DO UPDATE
SET team_id = CASE WHEN (SELECT country_id FROM teams WHERE id = EXCLUDED.team_id) IS NULL
                   THEN EXCLUDED.team_id ELSE players.team_id END,
    position = EXCLUDED.position,
    nationality = coalesce(EXCLUDED.nationality, players.nationality),
    shirt_number = CASE WHEN (SELECT country_id FROM teams WHERE id = EXCLUDED.team_id) IS NULL
                        THEN coalesce(EXCLUDED.shirt_number, players.shirt_number) ELSE players.shirt_number END,
    updated_at = now()
`

type UpsertSquadPlayerParams struct {
	FlashscoreID string
	TeamID       pgtype.UUID
	Name         string
	Nationality  pgtype.Text
	ShirtNumber  pgtype.Int2
	Position     pgtype.Text
}

// A club's squad page is its current list: it sets team, position, and number.
// A national team's only sets position: the player keeps his club and club number.
// The name stays as lineups write it ("Husna A. M."), so both sources agree.
func (q *Queries) UpsertSquadPlayer(ctx context.Context, arg UpsertSquadPlayerParams) error {
	_, err := q.db.Exec(ctx, upsertSquadPlayer,
		arg.FlashscoreID,
		arg.TeamID,
		arg.Name,
		arg.Nationality,
		arg.ShirtNumber,
		arg.Position,
	)
	return err
}

const upsertTeam = `-- name: UpsertTeam :one
INSERT INTO teams (flashscore_id, name, short_name, logo_source_url, country_id, flashscore_slug, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (flashscore_id) DO UPDATE
SET name = EXCLUDED.name,
    flashscore_slug = coalesce(EXCLUDED.flashscore_slug, teams.flashscore_slug),
    -- Only national team pages know a team's country; a league page never clears it.
    country_id = coalesce(EXCLUDED.country_id, teams.country_id),
    short_name = EXCLUDED.short_name,
    -- A new source clears the stored copy so the ingestor downloads it again.
    logo_url = CASE WHEN teams.logo_source_url IS DISTINCT FROM EXCLUDED.logo_source_url THEN NULL ELSE teams.logo_url END,
    logo_source_url = EXCLUDED.logo_source_url,
    updated_at = now()
RETURNING id
`

type UpsertTeamParams struct {
	FlashscoreID   string
	Name           string
	ShortName      string
	LogoSourceUrl  pgtype.Text
	CountryID      pgtype.UUID
	FlashscoreSlug pgtype.Text
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTeam,
		arg.FlashscoreID,
		arg.Name,
		arg.ShortName,
		arg.LogoSourceUrl,
		arg.CountryID,
		arg.FlashscoreSlug,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertTeamPageCompetition = `-- name: UpsertTeamPageCompetition :one
INSERT INTO competitions (slug, name, country_id, type, flashscore_path, scraped, sort_order)
VALUES ($1, $2, $3, 'cup', $4, false, 100)
ON CONFLICT (flashscore_path) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertTeamPageCompetitionParams struct {
	Slug           string
	Name           string
	CountryID      pgtype.UUID
	FlashscorePath string
}

// A competition seen on a national team's page; see migration 0020.
func (q *Queries) UpsertTeamPageCompetition(ctx context.Context, arg UpsertTeamPageCompetitionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTeamPageCompetition,
		arg.Slug,
		arg.Name,
		arg.CountryID,
		arg.FlashscorePath,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
