// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: football.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (flashscore_id, season, home_team_id, away_team_id, status, match_time, home_score, away_score, data_as_of, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
ON CONFLICT (flashscore_id) DO UPDATE
SET status = EXCLUDED.status,
    match_time = EXCLUDED.match_time,
    home_score = EXCLUDED.home_score,
    away_score = EXCLUDED.away_score,
    data_as_of = now(),
    updated_at = now()
RETURNING id
`

type UpsertMatchParams struct {
	FlashscoreID string
	Season       int16
	HomeTeamID   pgtype.UUID
	AwayTeamID   pgtype.UUID
	Status       string
	MatchTime    pgtype.Timestamptz
	HomeScore    pgtype.Int2
	AwayScore    pgtype.Int2
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMatch,
		arg.FlashscoreID,
		arg.Season,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.Status,
		arg.MatchTime,
		arg.HomeScore,
		arg.AwayScore,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertStanding = `-- name: UpsertStanding :exec
INSERT INTO standings (season, team_id, rank, points, form, zone, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (season, team_id) DO UPDATE
SET rank = EXCLUDED.rank,
    points = EXCLUDED.points,
    form = EXCLUDED.form,
    zone = EXCLUDED.zone,
    updated_at = now()
`

type UpsertStandingParams struct {
	Season int16
	TeamID pgtype.UUID
	Rank   int16
	Points int16
	Form   pgtype.Text
	Zone   pgtype.Text
}

func (q *Queries) UpsertStanding(ctx context.Context, arg UpsertStandingParams) error {
	_, err := q.db.Exec(ctx, upsertStanding,
		arg.Season,
		arg.TeamID,
		arg.Rank,
		arg.Points,
		arg.Form,
		arg.Zone,
	)
	return err
}

const upsertTeam = `-- name: UpsertTeam :one
INSERT INTO teams (flashscore_id, name, short_name, logo_url, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (flashscore_id) DO UPDATE
SET name = EXCLUDED.name,
    short_name = EXCLUDED.short_name,
    logo_url = EXCLUDED.logo_url,
    updated_at = now()
RETURNING id
`

type UpsertTeamParams struct {
	FlashscoreID string
	Name         string
	ShortName    string
	LogoUrl      pgtype.Text
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTeam,
		arg.FlashscoreID,
		arg.Name,
		arg.ShortName,
		arg.LogoUrl,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
