// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: football.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLiveCandidates = `-- name: ListLiveCandidates :many
SELECT id, flashscore_id, home_team_id, away_team_id
FROM matches
WHERE status = 'live'
   OR (status = 'scheduled' AND match_time <= now() AND match_time > now() - interval '3 hours')
`

type ListLiveCandidatesRow struct {
	ID           pgtype.UUID
	FlashscoreID string
	HomeTeamID   pgtype.UUID
	AwayTeamID   pgtype.UUID
}

// Live matches, plus scheduled ones whose kick-off has passed but the league page has not caught up.
func (q *Queries) ListLiveCandidates(ctx context.Context) ([]ListLiveCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLiveCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveCandidatesRow
	for rows.Next() {
		var i ListLiveCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlashscoreID,
			&i.HomeTeamID,
			&i.AwayTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchLive = `-- name: UpdateMatchLive :exec
UPDATE matches
SET status = $2, stage = $3, stage_started_at = $4, home_score = $5, away_score = $6,
    data_as_of = now(), updated_at = now()
WHERE id = $1
`

type UpdateMatchLiveParams struct {
	ID             pgtype.UUID
	Status         string
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
}

func (q *Queries) UpdateMatchLive(ctx context.Context, arg UpdateMatchLiveParams) error {
	_, err := q.db.Exec(ctx, updateMatchLive,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.StageStartedAt,
		arg.HomeScore,
		arg.AwayScore,
	)
	return err
}

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (flashscore_id, season, home_team_id, away_team_id, status, match_time, home_score, away_score, stage, stage_started_at, data_as_of, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now())
ON CONFLICT (flashscore_id) DO UPDATE
SET status = EXCLUDED.status,
    stage = EXCLUDED.stage,
    stage_started_at = EXCLUDED.stage_started_at,
    match_time = EXCLUDED.match_time,
    home_score = EXCLUDED.home_score,
    away_score = EXCLUDED.away_score,
    data_as_of = now(),
    updated_at = now()
RETURNING id
`

type UpsertMatchParams struct {
	FlashscoreID   string
	Season         int16
	HomeTeamID     pgtype.UUID
	AwayTeamID     pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMatch,
		arg.FlashscoreID,
		arg.Season,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.Status,
		arg.MatchTime,
		arg.HomeScore,
		arg.AwayScore,
		arg.Stage,
		arg.StageStartedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertStanding = `-- name: UpsertStanding :exec
INSERT INTO standings (season, team_id, rank, points, form, zone, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (season, team_id) DO UPDATE
SET rank = EXCLUDED.rank,
    points = EXCLUDED.points,
    form = EXCLUDED.form,
    zone = EXCLUDED.zone,
    updated_at = now()
`

type UpsertStandingParams struct {
	Season int16
	TeamID pgtype.UUID
	Rank   int16
	Points int16
	Form   pgtype.Text
	Zone   pgtype.Text
}

func (q *Queries) UpsertStanding(ctx context.Context, arg UpsertStandingParams) error {
	_, err := q.db.Exec(ctx, upsertStanding,
		arg.Season,
		arg.TeamID,
		arg.Rank,
		arg.Points,
		arg.Form,
		arg.Zone,
	)
	return err
}

const upsertTeam = `-- name: UpsertTeam :one
INSERT INTO teams (flashscore_id, name, short_name, logo_url, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (flashscore_id) DO UPDATE
SET name = EXCLUDED.name,
    short_name = EXCLUDED.short_name,
    logo_url = EXCLUDED.logo_url,
    updated_at = now()
RETURNING id
`

type UpsertTeamParams struct {
	FlashscoreID string
	Name         string
	ShortName    string
	LogoUrl      pgtype.Text
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTeam,
		arg.FlashscoreID,
		arg.Name,
		arg.ShortName,
		arg.LogoUrl,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
