// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatch = `-- name: GetMatch :one
SELECT id, season, status, match_time, home_score, away_score, stage, stage_started_at, home_team_id, away_team_id, home_name, home_short_name, home_logo_url, away_name, away_short_name, away_logo_url, competition_id, competition_slug, competition_name, competition_sort, round, phase FROM match_rows WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id pgtype.UUID) (MatchRow, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i MatchRow
	err := row.Scan(
		&i.ID,
		&i.Season,
		&i.Status,
		&i.MatchTime,
		&i.HomeScore,
		&i.AwayScore,
		&i.Stage,
		&i.StageStartedAt,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeName,
		&i.HomeShortName,
		&i.HomeLogoUrl,
		&i.AwayName,
		&i.AwayShortName,
		&i.AwayLogoUrl,
		&i.CompetitionID,
		&i.CompetitionSlug,
		&i.CompetitionName,
		&i.CompetitionSort,
		&i.Round,
		&i.Phase,
	)
	return i, err
}

const getMatchStats = `-- name: GetMatchStats :one
SELECT stats FROM match_statistics WHERE match_id = $1
`

func (q *Queries) GetMatchStats(ctx context.Context, matchID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMatchStats, matchID)
	var stats []byte
	err := row.Scan(&stats)
	return stats, err
}

const listMatchEvents = `-- name: ListMatchEvents :many
SELECT type, minute, player_name, team_id, related_player_name
FROM match_events
WHERE match_id = $1
ORDER BY NULLIF(substring(minute FROM '^\d+'), '')::int NULLS LAST, id
`

type ListMatchEventsRow struct {
	Type              string
	Minute            string
	PlayerName        string
	TeamID            pgtype.UUID
	RelatedPlayerName pgtype.Text
}

func (q *Queries) ListMatchEvents(ctx context.Context, matchID pgtype.UUID) ([]ListMatchEventsRow, error) {
	rows, err := q.db.Query(ctx, listMatchEvents, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchEventsRow
	for rows.Next() {
		var i ListMatchEventsRow
		if err := rows.Scan(
			&i.Type,
			&i.Minute,
			&i.PlayerName,
			&i.TeamID,
			&i.RelatedPlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchLineups = `-- name: ListMatchLineups :many
SELECT p.id, p.name, l.shirt_number, l.starter, l.team_id
FROM match_lineups l
JOIN players p ON p.id = l.player_id
WHERE l.match_id = $1
ORDER BY l.starter DESC, l.shirt_number NULLS LAST, p.name
`

type ListMatchLineupsRow struct {
	ID          pgtype.UUID
	Name        string
	ShirtNumber pgtype.Int2
	Starter     bool
	TeamID      pgtype.UUID
}

func (q *Queries) ListMatchLineups(ctx context.Context, matchID pgtype.UUID) ([]ListMatchLineupsRow, error) {
	rows, err := q.db.Query(ctx, listMatchLineups, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchLineupsRow
	for rows.Next() {
		var i ListMatchLineupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShirtNumber,
			&i.Starter,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT id, season, status, match_time, home_score, away_score, stage, stage_started_at, home_team_id, away_team_id, home_name, home_short_name, home_logo_url, away_name, away_short_name, away_logo_url, competition_id, competition_slug, competition_name, competition_sort, round, phase FROM match_rows
WHERE match_time >= $1 AND match_time < $2
  AND ($3::uuid IS NULL OR $3::uuid IN (home_team_id, away_team_id))
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR competition_slug = $5::text)
ORDER BY competition_sort, match_time, id
`

type ListMatchesParams struct {
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	TeamID      pgtype.UUID
	Status      pgtype.Text
	Competition pgtype.Text
}

func (q *Queries) ListMatches(ctx context.Context, arg ListMatchesParams) ([]MatchRow, error) {
	rows, err := q.db.Query(ctx, listMatches,
		arg.FromTime,
		arg.ToTime,
		arg.TeamID,
		arg.Status,
		arg.Competition,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchRow
	for rows.Next() {
		var i MatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.Status,
			&i.MatchTime,
			&i.HomeScore,
			&i.AwayScore,
			&i.Stage,
			&i.StageStartedAt,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeName,
			&i.HomeShortName,
			&i.HomeLogoUrl,
			&i.AwayName,
			&i.AwayShortName,
			&i.AwayLogoUrl,
			&i.CompetitionID,
			&i.CompetitionSlug,
			&i.CompetitionName,
			&i.CompetitionSort,
			&i.Round,
			&i.Phase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
