// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatch = `-- name: GetMatch :one
SELECT m.id, m.status, m.match_time, m.home_score, m.away_score, m.stage, m.stage_started_at,
       h.id AS home_id, h.name AS home_name, h.short_name AS home_short_name, h.logo_url AS home_logo_url,
       a.id AS away_id, a.name AS away_name, a.short_name AS away_short_name, a.logo_url AS away_logo_url
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE m.id = $1
`

type GetMatchRow struct {
	ID             pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	HomeID         pgtype.UUID
	HomeName       string
	HomeShortName  string
	HomeLogoUrl    pgtype.Text
	AwayID         pgtype.UUID
	AwayName       string
	AwayShortName  string
	AwayLogoUrl    pgtype.Text
}

func (q *Queries) GetMatch(ctx context.Context, id pgtype.UUID) (GetMatchRow, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i GetMatchRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.MatchTime,
		&i.HomeScore,
		&i.AwayScore,
		&i.Stage,
		&i.StageStartedAt,
		&i.HomeID,
		&i.HomeName,
		&i.HomeShortName,
		&i.HomeLogoUrl,
		&i.AwayID,
		&i.AwayName,
		&i.AwayShortName,
		&i.AwayLogoUrl,
	)
	return i, err
}

const getMatchStats = `-- name: GetMatchStats :one
SELECT stats FROM match_statistics WHERE match_id = $1
`

func (q *Queries) GetMatchStats(ctx context.Context, matchID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMatchStats, matchID)
	var stats []byte
	err := row.Scan(&stats)
	return stats, err
}

const listMatchEvents = `-- name: ListMatchEvents :many
SELECT type, minute, player_name, team_id
FROM match_events
WHERE match_id = $1
ORDER BY NULLIF(substring(minute FROM '^\d+'), '')::int NULLS LAST, id
`

type ListMatchEventsRow struct {
	Type       string
	Minute     string
	PlayerName string
	TeamID     pgtype.UUID
}

func (q *Queries) ListMatchEvents(ctx context.Context, matchID pgtype.UUID) ([]ListMatchEventsRow, error) {
	rows, err := q.db.Query(ctx, listMatchEvents, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchEventsRow
	for rows.Next() {
		var i ListMatchEventsRow
		if err := rows.Scan(
			&i.Type,
			&i.Minute,
			&i.PlayerName,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT m.id, m.status, m.match_time, m.home_score, m.away_score, m.stage, m.stage_started_at,
       h.id AS home_id, h.name AS home_name, h.short_name AS home_short_name, h.logo_url AS home_logo_url,
       a.id AS away_id, a.name AS away_name, a.short_name AS away_short_name, a.logo_url AS away_logo_url
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE m.match_time >= $1 AND m.match_time < $2
  AND ($3::uuid IS NULL OR $3::uuid IN (m.home_team_id, m.away_team_id))
  AND ($4::text IS NULL OR m.status = $4::text)
ORDER BY m.match_time, m.id
`

type ListMatchesParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
	TeamID   pgtype.UUID
	Status   pgtype.Text
}

type ListMatchesRow struct {
	ID             pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	HomeID         pgtype.UUID
	HomeName       string
	HomeShortName  string
	HomeLogoUrl    pgtype.Text
	AwayID         pgtype.UUID
	AwayName       string
	AwayShortName  string
	AwayLogoUrl    pgtype.Text
}

func (q *Queries) ListMatches(ctx context.Context, arg ListMatchesParams) ([]ListMatchesRow, error) {
	rows, err := q.db.Query(ctx, listMatches,
		arg.FromTime,
		arg.ToTime,
		arg.TeamID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesRow
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.MatchTime,
			&i.HomeScore,
			&i.AwayScore,
			&i.Stage,
			&i.StageStartedAt,
			&i.HomeID,
			&i.HomeName,
			&i.HomeShortName,
			&i.HomeLogoUrl,
			&i.AwayID,
			&i.AwayName,
			&i.AwayShortName,
			&i.AwayLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
