// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Competition struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	Type           string
	FlashscorePath string
	Active         bool
	SortOrder      int16
	CountryID      pgtype.UUID
	Scraped        bool
}

type Country struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	SortOrder int16
}

type Match struct {
	ID             pgtype.UUID
	FlashscoreID   string
	Season         int16
	HomeTeamID     pgtype.UUID
	AwayTeamID     pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	DataAsOf       pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	CompetitionID  pgtype.UUID
	Round          pgtype.Text
	Phase          pgtype.Text
}

type MatchEvent struct {
	ID                  pgtype.UUID
	MatchID             pgtype.UUID
	FlashscoreID        string
	Type                string
	Minute              string
	PlayerName          string
	TeamID              pgtype.UUID
	UpdatedAt           pgtype.Timestamptz
	PlayerFlashscoreID  pgtype.Text
	RelatedPlayerName   pgtype.Text
	RelatedFlashscoreID pgtype.Text
}

type MatchLineup struct {
	MatchID     pgtype.UUID
	PlayerID    pgtype.UUID
	TeamID      pgtype.UUID
	ShirtNumber pgtype.Int2
	Starter     bool
}

type MatchRow struct {
	ID              pgtype.UUID
	Season          int16
	Status          string
	MatchTime       pgtype.Timestamptz
	HomeScore       pgtype.Int2
	AwayScore       pgtype.Int2
	Stage           pgtype.Int2
	StageStartedAt  pgtype.Timestamptz
	HomeTeamID      pgtype.UUID
	AwayTeamID      pgtype.UUID
	HomeName        string
	HomeShortName   string
	HomeLogoUrl     pgtype.Text
	AwayName        string
	AwayShortName   string
	AwayLogoUrl     pgtype.Text
	CompetitionID   pgtype.UUID
	CompetitionSlug string
	CompetitionName string
	CompetitionSort int16
	Round           pgtype.Text
	Phase           pgtype.Text
}

type MatchStatistic struct {
	MatchID   pgtype.UUID
	Stats     []byte
	UpdatedAt pgtype.Timestamptz
}

type News struct {
	ID          pgtype.UUID
	Slug        string
	Category    string
	Title       string
	Summary     string
	Body        string
	ImageUrl    pgtype.Text
	AuthorID    pgtype.UUID
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NewsLink struct {
	NewsID   pgtype.UUID
	MatchID  pgtype.UUID
	TeamID   pgtype.UUID
	PlayerID pgtype.UUID
}

type Player struct {
	ID             pgtype.UUID
	FlashscoreID   string
	TeamID         pgtype.UUID
	Name           string
	AvatarUrl      pgtype.Text
	Position       pgtype.Text
	Nationality    pgtype.Text
	UpdatedAt      pgtype.Timestamptz
	ShirtNumber    pgtype.Int2
	PhotoSourceUrl pgtype.Text
	PhotoUrl       pgtype.Text
}

type Session struct {
	TokenHash []byte
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	Ip        *netip.Addr
}

type Team struct {
	ID            pgtype.UUID
	FlashscoreID  string
	Name          string
	ShortName     string
	LogoUrl       pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	LogoSourceUrl pgtype.Text
	CountryID     pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
