// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNewsLink = `-- name: AddNewsLink :exec
INSERT INTO news_links (news_id, match_id, team_id, player_id)
VALUES ($1, $2, $3, $4)
`

type AddNewsLinkParams struct {
	NewsID   pgtype.UUID
	MatchID  pgtype.UUID
	TeamID   pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) AddNewsLink(ctx context.Context, arg AddNewsLinkParams) error {
	_, err := q.db.Exec(ctx, addNewsLink,
		arg.NewsID,
		arg.MatchID,
		arg.TeamID,
		arg.PlayerID,
	)
	return err
}

const createNews = `-- name: CreateNews :one
INSERT INTO news (slug, category, title, summary, body, image_url, author_id, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateNewsParams struct {
	Slug        string
	Category    string
	Title       string
	Summary     string
	Body        string
	ImageUrl    pgtype.Text
	AuthorID    pgtype.UUID
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createNews,
		arg.Slug,
		arg.Category,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.ImageUrl,
		arg.AuthorID,
		arg.PublishedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteNews = `-- name: DeleteNews :execrows
DELETE FROM news WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNews, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNewsLinks = `-- name: DeleteNewsLinks :exec
DELETE FROM news_links WHERE news_id = $1
`

func (q *Queries) DeleteNewsLinks(ctx context.Context, newsID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNewsLinks, newsID)
	return err
}

const getNews = `-- name: GetNews :one
SELECT id, slug, category, title, summary, body, image_url, published_at, created_at, updated_at
FROM news
WHERE id = $1
`

type GetNewsRow struct {
	ID          pgtype.UUID
	Slug        string
	Category    string
	Title       string
	Summary     string
	Body        string
	ImageUrl    pgtype.Text
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetNews(ctx context.Context, id pgtype.UUID) (GetNewsRow, error) {
	row := q.db.QueryRow(ctx, getNews, id)
	var i GetNewsRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedNewsBySlug = `-- name: GetPublishedNewsBySlug :one
SELECT id, slug, category, title, summary, body, image_url, published_at
FROM news
WHERE slug = $1 AND published_at IS NOT NULL AND published_at <= now()
`

type GetPublishedNewsBySlugRow struct {
	ID          pgtype.UUID
	Slug        string
	Category    string
	Title       string
	Summary     string
	Body        string
	ImageUrl    pgtype.Text
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) GetPublishedNewsBySlug(ctx context.Context, slug string) (GetPublishedNewsBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedNewsBySlug, slug)
	var i GetPublishedNewsBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.PublishedAt,
	)
	return i, err
}

const listAllNews = `-- name: ListAllNews :many
SELECT id, slug, category, title, published_at, updated_at
FROM news
ORDER BY updated_at DESC
LIMIT 100
`

type ListAllNewsRow struct {
	ID          pgtype.UUID
	Slug        string
	Category    string
	Title       string
	PublishedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Editor view: drafts included, newest edits first.
func (q *Queries) ListAllNews(ctx context.Context) ([]ListAllNewsRow, error) {
	rows, err := q.db.Query(ctx, listAllNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllNewsRow
	for rows.Next() {
		var i ListAllNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.Title,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsLinks = `-- name: ListNewsLinks :many
SELECT match_id, team_id, player_id FROM news_links WHERE news_id = $1
`

type ListNewsLinksRow struct {
	MatchID  pgtype.UUID
	TeamID   pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) ListNewsLinks(ctx context.Context, newsID pgtype.UUID) ([]ListNewsLinksRow, error) {
	rows, err := q.db.Query(ctx, listNewsLinks, newsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsLinksRow
	for rows.Next() {
		var i ListNewsLinksRow
		if err := rows.Scan(&i.MatchID, &i.TeamID, &i.PlayerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedNews = `-- name: ListPublishedNews :many
SELECT n.id, n.slug, n.category, n.title, n.summary, n.image_url, n.published_at
FROM news n
WHERE n.published_at IS NOT NULL AND n.published_at <= now()
  AND ($1::uuid IS NULL OR EXISTS (SELECT 1 FROM news_links l WHERE l.news_id = n.id AND l.match_id = $1::uuid))
  AND ($2::uuid IS NULL OR EXISTS (SELECT 1 FROM news_links l WHERE l.news_id = n.id AND l.team_id = $2::uuid))
  AND ($3::uuid IS NULL OR EXISTS (SELECT 1 FROM news_links l WHERE l.news_id = n.id AND l.player_id = $3::uuid))
  AND ($4::timestamptz IS NULL
       OR (n.published_at, n.id) < ($4::timestamptz, $5::uuid))
ORDER BY n.published_at DESC, n.id DESC
LIMIT $6
`

type ListPublishedNewsParams struct {
	MatchID           pgtype.UUID
	TeamID            pgtype.UUID
	PlayerID          pgtype.UUID
	CursorPublishedAt pgtype.Timestamptz
	CursorID          pgtype.UUID
	RowLimit          int32
}

type ListPublishedNewsRow struct {
	ID          pgtype.UUID
	Slug        string
	Category    string
	Title       string
	Summary     string
	ImageUrl    pgtype.Text
	PublishedAt pgtype.Timestamptz
}

// Keyset pagination on (published_at, id), newest first.
func (q *Queries) ListPublishedNews(ctx context.Context, arg ListPublishedNewsParams) ([]ListPublishedNewsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedNews,
		arg.MatchID,
		arg.TeamID,
		arg.PlayerID,
		arg.CursorPublishedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedNewsRow
	for rows.Next() {
		var i ListPublishedNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.Title,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNews = `-- name: UpdateNews :one
UPDATE news
SET slug = $2, category = $3, title = $4, summary = $5, body = $6, image_url = $7,
    published_at = CASE WHEN $8::boolean THEN coalesce(published_at, now()) ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id
`

type UpdateNewsParams struct {
	ID       pgtype.UUID
	Slug     string
	Category string
	Title    string
	Summary  string
	Body     string
	ImageUrl pgtype.Text
	Publish  bool
}

// published_at keeps its first value on re-save, so editing a live article does not bump it to the top.
func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateNews,
		arg.ID,
		arg.Slug,
		arg.Category,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.ImageUrl,
		arg.Publish,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
