// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlayer = `-- name: GetPlayer :one
SELECT p.id, p.flashscore_id, p.name, p.shirt_number, p.position, p.nationality, p.photo_url,
       t.id AS team_id, t.name AS team_name, t.short_name AS team_short_name, t.logo_url AS team_logo_url
FROM players p
LEFT JOIN teams t ON t.id = p.team_id
WHERE p.id = $1
`

type GetPlayerRow struct {
	ID            pgtype.UUID
	FlashscoreID  string
	Name          string
	ShirtNumber   pgtype.Int2
	Position      pgtype.Text
	Nationality   pgtype.Text
	PhotoUrl      pgtype.Text
	TeamID        pgtype.UUID
	TeamName      pgtype.Text
	TeamShortName pgtype.Text
	TeamLogoUrl   pgtype.Text
}

func (q *Queries) GetPlayer(ctx context.Context, id pgtype.UUID) (GetPlayerRow, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.FlashscoreID,
		&i.Name,
		&i.ShirtNumber,
		&i.Position,
		&i.Nationality,
		&i.PhotoUrl,
		&i.TeamID,
		&i.TeamName,
		&i.TeamShortName,
		&i.TeamLogoUrl,
	)
	return i, err
}

const listPlayerMatches = `-- name: ListPlayerMatches :many
SELECT m.id, m.match_time, m.status, m.home_score, m.away_score, m.round,
       c.slug AS competition_slug, c.name AS competition_name,
       l.starter, l.team_id,
       h.name AS home_name, a.name AS away_name,
       m.home_team_id,
       EXISTS (SELECT 1 FROM match_events e WHERE e.match_id = m.id AND e.type = 'Substitution'
                 AND e.player_flashscore_id = $1::text) AS subbed_on,
       (SELECT count(*) FROM match_events e WHERE e.match_id = m.id AND e.type IN ('Goal', 'Penalty')
          AND e.player_flashscore_id = $1::text)::int AS goals,
       (SELECT count(*) FROM match_events e WHERE e.match_id = m.id AND e.type IN ('Goal', 'Penalty')
          AND e.related_flashscore_id = $1::text)::int AS assists,
       (SELECT count(*) FROM match_events e WHERE e.match_id = m.id AND e.type = 'Yellow Card'
          AND e.player_flashscore_id = $1::text)::int AS yellow,
       (SELECT count(*) FROM match_events e WHERE e.match_id = m.id AND e.type IN ('Red Card', 'Yellow/Red Card')
          AND e.player_flashscore_id = $1::text)::int AS red
FROM match_lineups l
JOIN matches m ON m.id = l.match_id
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
JOIN competitions c ON c.id = m.competition_id
WHERE l.player_id = $2::uuid AND m.season = $3::smallint
  AND ($4::uuid IS NULL OR m.competition_id = $4::uuid)
ORDER BY m.match_time DESC
`

type ListPlayerMatchesParams struct {
	FlashscoreID  string
	PlayerID      pgtype.UUID
	Season        int16
	CompetitionID pgtype.UUID
}

type ListPlayerMatchesRow struct {
	ID              pgtype.UUID
	MatchTime       pgtype.Timestamptz
	Status          string
	HomeScore       pgtype.Int2
	AwayScore       pgtype.Int2
	Round           pgtype.Text
	CompetitionSlug string
	CompetitionName string
	Starter         bool
	TeamID          pgtype.UUID
	HomeName        string
	AwayName        string
	HomeTeamID      pgtype.UUID
	SubbedOn        bool
	Goals           int32
	Assists         int32
	Yellow          int32
	Red             int32
}

// Every match the player was listed for in a season (optionally one competition), newest first, with what they did in it.
func (q *Queries) ListPlayerMatches(ctx context.Context, arg ListPlayerMatchesParams) ([]ListPlayerMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerMatches,
		arg.FlashscoreID,
		arg.PlayerID,
		arg.Season,
		arg.CompetitionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerMatchesRow
	for rows.Next() {
		var i ListPlayerMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchTime,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.Round,
			&i.CompetitionSlug,
			&i.CompetitionName,
			&i.Starter,
			&i.TeamID,
			&i.HomeName,
			&i.AwayName,
			&i.HomeTeamID,
			&i.SubbedOn,
			&i.Goals,
			&i.Assists,
			&i.Yellow,
			&i.Red,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
