// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchNews = `-- name: SearchNews :many
SELECT slug, title, category, published_at
FROM news
WHERE published_at IS NOT NULL AND published_at <= now()
  AND $1::text <% title
ORDER BY word_similarity($1::text, title) DESC, published_at DESC
LIMIT 5
`

type SearchNewsRow struct {
	Slug        string
	Title       string
	Category    string
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) SearchNews(ctx context.Context, q_ string) ([]SearchNewsRow, error) {
	rows, err := q.db.Query(ctx, searchNews, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNewsRow
	for rows.Next() {
		var i SearchNewsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT p.id, p.name, p.shirt_number, t.name AS team_name
FROM players p
LEFT JOIN teams t ON t.id = p.team_id
WHERE $1::text <% p.name
ORDER BY word_similarity($1::text, p.name) DESC, p.name
LIMIT 10
`

type SearchPlayersRow struct {
	ID          pgtype.UUID
	Name        string
	ShirtNumber pgtype.Int2
	TeamName    pgtype.Text
}

func (q *Queries) SearchPlayers(ctx context.Context, q_ string) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPlayersRow
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShirtNumber,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeams = `-- name: SearchTeams :many
SELECT id, name, short_name, logo_url
FROM teams
WHERE $1::text <% name
ORDER BY word_similarity($1::text, name) DESC, name
LIMIT 5
`

type SearchTeamsRow struct {
	ID        pgtype.UUID
	Name      string
	ShortName string
	LogoUrl   pgtype.Text
}

func (q *Queries) SearchTeams(ctx context.Context, q_ string) ([]SearchTeamsRow, error) {
	rows, err := q.db.Query(ctx, searchTeams, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTeamsRow
	for rows.Next() {
		var i SearchTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
