// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: standings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompetition = `-- name: GetCompetition :one
SELECT c.id, c.slug, c.name, n.name AS country, n.slug AS country_slug, c.type,
       coalesce((SELECT max(season) FROM matches m WHERE m.competition_id = c.id), 0)::smallint AS season
FROM competitions c
JOIN countries n ON n.id = c.country_id
WHERE c.slug = $1
`

type GetCompetitionRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Country     string
	CountrySlug string
	Type        string
	Season      int16
}

func (q *Queries) GetCompetition(ctx context.Context, slug string) (GetCompetitionRow, error) {
	row := q.db.QueryRow(ctx, getCompetition, slug)
	var i GetCompetitionRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Country,
		&i.CountrySlug,
		&i.Type,
		&i.Season,
	)
	return i, err
}

const latestSeason = `-- name: LatestSeason :one
SELECT coalesce(max(season), 0)::smallint FROM matches
`

func (q *Queries) LatestSeason(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, latestSeason)
	var column_1 int16
	err := row.Scan(&column_1)
	return column_1, err
}

const listCompetitions = `-- name: ListCompetitions :many
SELECT c.id, c.slug, c.name, n.name AS country, n.slug AS country_slug, c.type,
       coalesce((SELECT max(season) FROM matches m WHERE m.competition_id = c.id), 0)::smallint AS season
FROM competitions c
JOIN countries n ON n.id = c.country_id
WHERE c.active
ORDER BY n.sort_order, c.sort_order
`

type ListCompetitionsRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Country     string
	CountrySlug string
	Type        string
	Season      int16
}

// Each competition with its latest season (0 until the ingestor has stored a match).
func (q *Queries) ListCompetitions(ctx context.Context) ([]ListCompetitionsRow, error) {
	rows, err := q.db.Query(ctx, listCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionsRow
	for rows.Next() {
		var i ListCompetitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Country,
			&i.CountrySlug,
			&i.Type,
			&i.Season,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupPairings = `-- name: ListGroupPairings :many
SELECT DISTINCT home_team_id, away_team_id
FROM matches
WHERE competition_id = $1::uuid AND season = $2::smallint AND phase IS NULL
`

type ListGroupPairingsParams struct {
	CompetitionID pgtype.UUID
	Season        int16
}

type ListGroupPairingsRow struct {
	HomeTeamID pgtype.UUID
	AwayTeamID pgtype.UUID
}

// Who met whom in the group stage; a cup's groups are the connected components.
func (q *Queries) ListGroupPairings(ctx context.Context, arg ListGroupPairingsParams) ([]ListGroupPairingsRow, error) {
	rows, err := q.db.Query(ctx, listGroupPairings, arg.CompetitionID, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupPairingsRow
	for rows.Next() {
		var i ListGroupPairingsRow
		if err := rows.Scan(&i.HomeTeamID, &i.AwayTeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandings = `-- name: ListStandings :many
WITH season_teams AS (
    SELECT home_team_id AS team_id FROM matches WHERE competition_id = $1::uuid AND season = $2::smallint AND phase IS NULL
    UNION
    SELECT away_team_id FROM matches WHERE competition_id = $1::uuid AND season = $2::smallint AND phase IS NULL
),
results AS (
    SELECT home_team_id AS team_id, home_score AS gf, away_score AS ga, match_time
    FROM matches WHERE competition_id = $1::uuid AND season = $2::smallint AND phase IS NULL AND status = 'finished'
    UNION ALL
    SELECT away_team_id, away_score, home_score, match_time
    FROM matches WHERE competition_id = $1::uuid AND season = $2::smallint AND phase IS NULL AND status = 'finished'
),
totals AS (
    SELECT st.team_id,
           count(r.team_id)::int                       AS played,
           count(*) FILTER (WHERE r.gf > r.ga)::int    AS won,
           count(*) FILTER (WHERE r.gf = r.ga)::int    AS drawn,
           count(*) FILTER (WHERE r.gf < r.ga)::int    AS lost,
           coalesce(sum(r.gf), 0)::int                 AS goals_for,
           coalesce(sum(r.ga), 0)::int                 AS goals_against,
           coalesce((array_agg(CASE WHEN r.gf > r.ga THEN 'W' WHEN r.gf = r.ga THEN 'D' ELSE 'L' END
                                ORDER BY r.match_time DESC) FILTER (WHERE r.team_id IS NOT NULL))[1:5],
                    '{}')::text[]                     AS form
    FROM season_teams st
    LEFT JOIN results r ON r.team_id = st.team_id
    GROUP BY st.team_id
)
SELECT t.id, t.name, t.short_name, t.logo_url,
       tt.played, tt.won, tt.drawn, tt.lost, tt.goals_for, tt.goals_against,
       (tt.won * 3 + tt.drawn)::int AS points,
       tt.form
FROM totals tt
JOIN teams t ON t.id = tt.team_id
ORDER BY points DESC, tt.goals_for - tt.goals_against DESC, tt.goals_for DESC, t.name
`

type ListStandingsParams struct {
	CompetitionID pgtype.UUID
	Season        int16
}

type ListStandingsRow struct {
	ID           pgtype.UUID
	Name         string
	ShortName    string
	LogoUrl      pgtype.Text
	Played       int32
	Won          int32
	Drawn        int32
	Lost         int32
	GoalsFor     int32
	GoalsAgainst int32
	Points       int32
	Form         []string
}

// Every team with a match in the season, ranked by points, goal difference, goals scored.
// ponytail: Liga 1 breaks ties head-to-head first; add that if two teams ever tie on points at season end.
func (q *Queries) ListStandings(ctx context.Context, arg ListStandingsParams) ([]ListStandingsRow, error) {
	rows, err := q.db.Query(ctx, listStandings, arg.CompetitionID, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStandingsRow
	for rows.Next() {
		var i ListStandingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.LogoUrl,
			&i.Played,
			&i.Won,
			&i.Drawn,
			&i.Lost,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.Points,
			&i.Form,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
