// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: standings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestSeason = `-- name: LatestSeason :one
SELECT coalesce(max(season), 0)::smallint FROM matches
`

func (q *Queries) LatestSeason(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, latestSeason)
	var column_1 int16
	err := row.Scan(&column_1)
	return column_1, err
}

const listStandings = `-- name: ListStandings :many
WITH season_teams AS (
    SELECT home_team_id AS team_id FROM matches WHERE season = $1::smallint
    UNION
    SELECT away_team_id FROM matches WHERE season = $1::smallint
),
results AS (
    SELECT home_team_id AS team_id, home_score AS gf, away_score AS ga, match_time
    FROM matches WHERE season = $1::smallint AND status = 'finished'
    UNION ALL
    SELECT away_team_id, away_score, home_score, match_time
    FROM matches WHERE season = $1::smallint AND status = 'finished'
),
totals AS (
    SELECT st.team_id,
           count(r.team_id)::int                       AS played,
           count(*) FILTER (WHERE r.gf > r.ga)::int    AS won,
           count(*) FILTER (WHERE r.gf = r.ga)::int    AS drawn,
           count(*) FILTER (WHERE r.gf < r.ga)::int    AS lost,
           coalesce(sum(r.gf), 0)::int                 AS goals_for,
           coalesce(sum(r.ga), 0)::int                 AS goals_against,
           coalesce((array_agg(CASE WHEN r.gf > r.ga THEN 'W' WHEN r.gf = r.ga THEN 'D' ELSE 'L' END
                                ORDER BY r.match_time DESC) FILTER (WHERE r.team_id IS NOT NULL))[1:5],
                    '{}')::text[]                     AS form
    FROM season_teams st
    LEFT JOIN results r ON r.team_id = st.team_id
    GROUP BY st.team_id
)
SELECT t.id, t.name, t.short_name, t.logo_url,
       tt.played, tt.won, tt.drawn, tt.lost, tt.goals_for, tt.goals_against,
       (tt.won * 3 + tt.drawn)::int AS points,
       tt.form
FROM totals tt
JOIN teams t ON t.id = tt.team_id
ORDER BY points DESC, tt.goals_for - tt.goals_against DESC, tt.goals_for DESC, t.name
`

type ListStandingsRow struct {
	ID           pgtype.UUID
	Name         string
	ShortName    string
	LogoUrl      pgtype.Text
	Played       int32
	Won          int32
	Drawn        int32
	Lost         int32
	GoalsFor     int32
	GoalsAgainst int32
	Points       int32
	Form         []string
}

// Every team with a match in the season, ranked by points, goal difference, goals scored.
// ponytail: Liga 1 breaks ties head-to-head first; add that if two teams ever tie on points at season end.
func (q *Queries) ListStandings(ctx context.Context, season int16) ([]ListStandingsRow, error) {
	rows, err := q.db.Query(ctx, listStandings, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStandingsRow
	for rows.Next() {
		var i ListStandingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.LogoUrl,
			&i.Played,
			&i.Won,
			&i.Drawn,
			&i.Lost,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.Points,
			&i.Form,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
