// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTeam = `-- name: GetTeam :one
SELECT id, name, short_name, logo_url FROM teams WHERE id = $1
`

type GetTeamRow struct {
	ID        pgtype.UUID
	Name      string
	ShortName string
	LogoUrl   pgtype.Text
}

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (GetTeamRow, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i GetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.LogoUrl,
	)
	return i, err
}

const listTeamRecentMatches = `-- name: ListTeamRecentMatches :many
SELECT m.id, m.status, m.match_time, m.home_score, m.away_score, m.stage, m.stage_started_at,
       h.id AS home_id, h.name AS home_name, h.short_name AS home_short_name, h.logo_url AS home_logo_url,
       a.id AS away_id, a.name AS away_name, a.short_name AS away_short_name, a.logo_url AS away_logo_url
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE $1 IN (m.home_team_id, m.away_team_id) AND m.status <> 'scheduled'
ORDER BY m.match_time DESC
LIMIT 5
`

type ListTeamRecentMatchesRow struct {
	ID             pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	HomeID         pgtype.UUID
	HomeName       string
	HomeShortName  string
	HomeLogoUrl    pgtype.Text
	AwayID         pgtype.UUID
	AwayName       string
	AwayShortName  string
	AwayLogoUrl    pgtype.Text
}

func (q *Queries) ListTeamRecentMatches(ctx context.Context, homeTeamID pgtype.UUID) ([]ListTeamRecentMatchesRow, error) {
	rows, err := q.db.Query(ctx, listTeamRecentMatches, homeTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRecentMatchesRow
	for rows.Next() {
		var i ListTeamRecentMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.MatchTime,
			&i.HomeScore,
			&i.AwayScore,
			&i.Stage,
			&i.StageStartedAt,
			&i.HomeID,
			&i.HomeName,
			&i.HomeShortName,
			&i.HomeLogoUrl,
			&i.AwayID,
			&i.AwayName,
			&i.AwayShortName,
			&i.AwayLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamSquad = `-- name: ListTeamSquad :many
SELECT p.id, p.name, p.shirt_number, p.position, p.nationality,
       (SELECT count(*) FROM match_lineups l JOIN matches m ON m.id = l.match_id
         WHERE l.player_id = p.id AND m.season = $1::smallint
           AND (l.starter OR EXISTS (SELECT 1 FROM match_events e
                                      WHERE e.match_id = l.match_id AND e.type = 'Substitution'
                                        AND e.player_flashscore_id = p.flashscore_id)))::int AS apps,
       (SELECT count(*) FROM match_events e JOIN matches m ON m.id = e.match_id
         WHERE e.player_flashscore_id = p.flashscore_id AND e.type IN ('Goal', 'Penalty')
           AND m.season = $1::smallint)::int AS goals,
       (SELECT count(*) FROM match_events e JOIN matches m ON m.id = e.match_id
         WHERE e.related_flashscore_id = p.flashscore_id AND e.type IN ('Goal', 'Penalty')
           AND m.season = $1::smallint)::int AS assists
FROM players p
WHERE p.team_id = $2::uuid
ORDER BY p.position = 'GK' DESC, p.shirt_number NULLS LAST, p.name
`

type ListTeamSquadParams struct {
	Season int16
	TeamID pgtype.UUID
}

type ListTeamSquadRow struct {
	ID          pgtype.UUID
	Name        string
	ShirtNumber pgtype.Int2
	Position    pgtype.Text
	Nationality pgtype.Text
	Apps        int32
	Goals       int32
	Assists     int32
}

// Current squad with season numbers. An appearance is a start or a substitution on.
func (q *Queries) ListTeamSquad(ctx context.Context, arg ListTeamSquadParams) ([]ListTeamSquadRow, error) {
	rows, err := q.db.Query(ctx, listTeamSquad, arg.Season, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamSquadRow
	for rows.Next() {
		var i ListTeamSquadRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShirtNumber,
			&i.Position,
			&i.Nationality,
			&i.Apps,
			&i.Goals,
			&i.Assists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamUpcomingMatches = `-- name: ListTeamUpcomingMatches :many
SELECT m.id, m.status, m.match_time, m.home_score, m.away_score, m.stage, m.stage_started_at,
       h.id AS home_id, h.name AS home_name, h.short_name AS home_short_name, h.logo_url AS home_logo_url,
       a.id AS away_id, a.name AS away_name, a.short_name AS away_short_name, a.logo_url AS away_logo_url
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE $1 IN (m.home_team_id, m.away_team_id) AND m.status = 'scheduled'
ORDER BY m.match_time
LIMIT 5
`

type ListTeamUpcomingMatchesRow struct {
	ID             pgtype.UUID
	Status         string
	MatchTime      pgtype.Timestamptz
	HomeScore      pgtype.Int2
	AwayScore      pgtype.Int2
	Stage          pgtype.Int2
	StageStartedAt pgtype.Timestamptz
	HomeID         pgtype.UUID
	HomeName       string
	HomeShortName  string
	HomeLogoUrl    pgtype.Text
	AwayID         pgtype.UUID
	AwayName       string
	AwayShortName  string
	AwayLogoUrl    pgtype.Text
}

func (q *Queries) ListTeamUpcomingMatches(ctx context.Context, homeTeamID pgtype.UUID) ([]ListTeamUpcomingMatchesRow, error) {
	rows, err := q.db.Query(ctx, listTeamUpcomingMatches, homeTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamUpcomingMatchesRow
	for rows.Next() {
		var i ListTeamUpcomingMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.MatchTime,
			&i.HomeScore,
			&i.AwayScore,
			&i.Stage,
			&i.StageStartedAt,
			&i.HomeID,
			&i.HomeName,
			&i.HomeShortName,
			&i.HomeLogoUrl,
			&i.AwayID,
			&i.AwayName,
			&i.AwayShortName,
			&i.AwayLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
